# Generated by Django 4.0.4 on 2022-04-26 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitedata', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rozetkasite',
            name='location',
        ),
    ]
