# Generated by Django 4.0.4 on 2022-04-26 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitedata', '0002_remove_rozetkasite_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rozetkasite',
            name='reviews',
            field=models.CharField(max_length=30, null=True, verbose_name='Reviews'),
        ),
    ]
