# Generated by Django 4.0.4 on 2022-04-26 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitedata', '0004_fotossite'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FotosSite',
            new_name='FoxtrotSite',
        ),
    ]
