# Generated by Django 4.0.4 on 2022-04-26 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitedata', '0006_promsite'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PromSite',
            new_name='ComfySite',
        ),
    ]
