# Generated by Django 4.0.4 on 2022-04-26 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitedata', '0007_rename_promsite_comfysite'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ComfySite',
            new_name='AlloSite',
        ),
    ]
