# Generated by Django 4.0.4 on 2022-04-26 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitedata', '0008_rename_comfysite_allosite'),
    ]

    operations = [
        migrations.CreateModel(
            name='ITBlockSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Title')),
                ('price', models.CharField(max_length=100, verbose_name='Price')),
                ('link', models.CharField(max_length=555, verbose_name='Link')),
                ('reviews', models.CharField(max_length=30, null=True, verbose_name='Reviews')),
            ],
        ),
    ]
