# Generated by Django 4.0.4 on 2022-04-26 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitedata', '0009_itblocksite'),
    ]

    operations = [
        migrations.AddField(
            model_name='allosite',
            name='image_link',
            field=models.CharField(max_length=555, null=True, verbose_name='Image link'),
        ),
        migrations.AddField(
            model_name='foxtrotsite',
            name='image_link',
            field=models.CharField(max_length=555, null=True, verbose_name='Image link'),
        ),
        migrations.AddField(
            model_name='itblocksite',
            name='image_link',
            field=models.CharField(max_length=555, null=True, verbose_name='Image link'),
        ),
        migrations.AddField(
            model_name='rozetkasite',
            name='image_link',
            field=models.CharField(max_length=555, null=True, verbose_name='Image link'),
        ),
    ]
